/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pbl.form;

import com.pbl.chart.ModelChart;
import com.pbl.service.TaskService;
import java.awt.Color;
import java.time.Month;
import java.time.format.TextStyle;
import java.util.Locale;

/**
 *
 * @author ADMIN
 */
public class ChartForm extends javax.swing.JPanel {

    /**
     * Creates new form ChartForm
     */
    public ChartForm(int userId) {
        initComponents();
        chart.addLegend("Đã hoàn thành", new Color(76, 175, 80));
        chart.addLegend("Chưa hoàn thành", new Color(244, 67, 54));
        TaskService service = new TaskService();
        for (int m = 1; m <= 6; m++) {
            // Đếm done & pending trong tháng m
            int doneCount = service.getCountByMonthAndStatus(userId, m, true);
            int pendingCount = service.getCountByMonthAndStatus(userId, m, false);
            // Lấy tên tháng (Jan, Feb,…)
            String monthName = Month.of(m)
                    .getDisplayName(TextStyle.SHORT, Locale.getDefault());
            chart.addData(new ModelChart(monthName, new double[]{doneCount, pendingCount}));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chart = new com.pbl.chart.Chart();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(119, 119, 119))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.pbl.chart.Chart chart;
    // End of variables declaration//GEN-END:variables
}
